#import "SwiftBridgeCore.h"
#import "em_proxy.h"
#import "minimuxer.h"
#include "libimobiledevice/libimobiledevice.h"
#include "libimobiledevice/diagnostics_relay.h"
#include "libimobiledevice/mobilebackup2.h"
#include "libimobiledevice/debugserver.h"
#include "libimobiledevice/heartbeat.h"
#include "libimobiledevice/installation_proxy.h"
#include "libimobiledevice/lockdown.h"
#include "libimobiledevice/mobile_image_mounter.h"
#include "libimobiledevice/sbservices.h"
#include "libimobiledevice/service.h"
#include "libimobiledevice-glue/utils.h"

#include "privatekits/CoreSVG.h"
#include "privatekits/CSIBitmapWrapper.h"
#include "privatekits/CSIGenerator.h"
#include "privatekits/CUIRenditionKey.h"
#include "privatekits/structs.h"
#include "privatekits/CUIThemeRendition.h"
#include "privatekits/CUIStructuredThemeStore.h"
#include "privatekits/CUICommonAssetStorage.h"
#include "privatekits/CUINamedLookup.h"
#include "privatekits/CUICatalog.h"
#include "privatekits/CoreUI.h"


int idevicebackup2_main(int argc, char *argv[]);
